export interface GameCategory {
  id: string
  name: string
  icon: string
  description: string
  words: string[]
}

export const gameCategories: GameCategory[] = [
  {
    id: "football",
    name: "Fútbol",
    icon: "⚽",
    description: "Jugadores, equipos, términos futbolísticos",
    words: [
      "Messi",
      "Ronaldo",
      "Pelé",
      "Maradona",
      "Neymar",
      "Mbappé",
      "Haaland",
      "Barcelona",
      "Real Madrid",
      "Manchester United",
      "Bayern Munich",
      "PSG",
      "Gol",
      "Penalti",
      "Córner",
      "Fuera de juego",
      "Tarjeta roja",
      "VAR",
      "Champions League",
      "Mundial",
      "Copa América",
      "Eurocopa",
      "Premier League",
      "Portero",
      "Defensa",
      "Centrocampista",
      "Delantero",
      "Árbitro",
      "Entrenador",
    ],
  },
  {
    id: "movies",
    name: "Cine",
    icon: "🎬",
    description: "Películas, actores, directores famosos",
    words: [
      "Titanic",
      "Avatar",
      "Avengers",
      "Star Wars",
      "Harry Potter",
      "Batman",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Scarlett Johansson",
      "Tom Hanks",
      "Spielberg",
      "Tarantino",
      "Christopher Nolan",
      "Martin Scorsese",
      "Oscar",
      "Hollywood",
      "Netflix",
      "Disney",
      "Marvel",
      "DC Comics",
      "Thriller",
      "Comedia",
      "Drama",
      "Acción",
      "Terror",
      "Ciencia ficción",
    ],
  },
  {
    id: "politics",
    name: "Política",
    icon: "🏛️",
    description: "Líderes mundiales, instituciones, conceptos políticos",
    words: [
      "Presidente",
      "Congreso",
      "Senado",
      "Constitución",
      "Democracia",
      "Biden",
      "Trump",
      "Putin",
      "Xi Jinping",
      "Macron",
      "Merkel",
      "ONU",
      "OTAN",
      "Unión Europea",
      "Casa Blanca",
      "Kremlin",
      "Elecciones",
      "Voto",
      "Campaña",
      "Partido político",
      "Oposición",
      "Izquierda",
      "Derecha",
      "Centro",
      "Liberal",
      "Conservador",
      "Socialista",
    ],
  },
  {
    id: "music",
    name: "Música",
    icon: "🎵",
    description: "Artistas, géneros, instrumentos musicales",
    words: [
      "Beatles",
      "Queen",
      "Michael Jackson",
      "Madonna",
      "Elvis",
      "Bob Dylan",
      "Taylor Swift",
      "Drake",
      "Beyoncé",
      "Ed Sheeran",
      "Adele",
      "Billie Eilish",
      "Rock",
      "Pop",
      "Jazz",
      "Blues",
      "Reggae",
      "Hip Hop",
      "Clásica",
      "Guitarra",
      "Piano",
      "Batería",
      "Violín",
      "Saxofón",
      "Trompeta",
      "Grammy",
      "Spotify",
      "iTunes",
      "Concierto",
      "Festival",
      "Álbum",
    ],
  },
  {
    id: "random",
    name: "Random",
    icon: "🎲",
    description: "Palabras variadas de diferentes categorías",
    words: [
      "Pizza",
      "Café",
      "Playa",
      "Montaña",
      "Libro",
      "Teléfono",
      "Coche",
      "Perro",
      "Gato",
      "Árbol",
      "Flor",
      "Sol",
      "Luna",
      "Perro",
      "Gato",
      "Árbol",
      "Flor",
      "Sol",
      "Luna",
      "Estrella",
      "Casa",
      "Escuela",
      "Hospital",
      "Parque",
      "Museo",
      "Teatro",
      "Agua",
      "Fuego",
      "Tierra",
      "Aire",
      "Tiempo",
      "Espacio",
      "Amor",
      "Amistad",
      "Familia",
      "Trabajo",
      "Dinero",
      "Salud",
    ],
  },
]

export function getRandomWords(words: string[], count: number): string[] {
  const shuffled = [...words].sort(() => 0.5 - Math.random())
  const selectedWord = shuffled[0]
  return Array(count).fill(selectedWord)
}
