export interface SubTheme {
  id: string
  label: string
  words: string[]
}

export interface Theme {
  id: string
  label: string
  icon: string
  description: string
  words: string[] // Pool "General"
  subThemes?: Record<string, SubTheme>
}

export const themes: Theme[] = [
  {
    id: "football",
    label: "Fútbol",
    icon: "⚽",
    description: "Jugadores, equipos, términos futbolísticos",
    words: [
      // General
      "Fútbol",
      "Gol",
      "Penalti",
      "Córner",
      "Fuera de juego",
      "Tarjeta roja",
      "VAR",
      "Portero",
      "Defensa",
      "Centrocampista",
      "Delantero",
      "Árbitro",
      "Entrenador",
      "Estadio",
      "Hinchada",
      "Pelota",
      "Cancha",
      "Arco",
      "Lateral",
      "Tiro libre",
    ],
    subThemes: {
      arg: {
        id: "arg",
        label: "Fútbol argentino",
        words: [
          "Boca Juniors",
          "River Plate",
          "Racing",
          "Independiente",
          "San Lorenzo",
          "Estudiantes",
          "Gimnasia",
          "Newell's",
          "Rosario Central",
          "Vélez",
          "Lanús",
          "Banfield",
          "Huracán",
          "Argentinos Juniors",
          "Talleres",
          "Godoy Cruz",
          "Superliga",
          "Primera División",
          "Bombonera",
          "Monumental",
          "Cilindro",
          "Libertadores de América",
          "El Gasómetro",
          "Pincha",
          "Lobo",
          "Fortín",
          "Granate",
          "Taladro",
          "Globo",
          "Bicho",
        ],
      },
      epl: {
        id: "epl",
        label: "Liga inglesa",
        words: [
          "Manchester United",
          "Manchester City",
          "Liverpool",
          "Chelsea",
          "Arsenal",
          "Tottenham",
          "Newcastle",
          "Brighton",
          "Aston Villa",
          "West Ham",
          "Crystal Palace",
          "Fulham",
          "Brentford",
          "Wolves",
          "Everton",
          "Nottingham Forest",
          "Burnley",
          "Sheffield United",
          "Luton Town",
          "Premier League",
          "Old Trafford",
          "Etihad",
          "Anfield",
          "Stamford Bridge",
          "Emirates",
          "Wembley",
          "FA Cup",
          "Carabao Cup",
          "Community Shield",
        ],
      },
      retired: {
        id: "retired",
        label: "Jugadores retirados",
        words: [
          "Pelé",
          "Maradona",
          "Ronaldinho",
          "Zidane",
          "Ronaldo Nazário",
          "Roberto Carlos",
          "Kaká",
          "Pirlo",
          "Totti",
          "Gerrard",
          "Lampard",
          "Scholes",
          "Beckham",
          "Henry",
          "Bergkamp",
          "Cruyff",
          "Platini",
          "Baggio",
          "Del Piero",
          "Maldini",
          "Baresi",
          "Nesta",
          "Cannavaro",
          "Buffon",
          "Casillas",
          "Xavi",
          "Iniesta",
          "Puyol",
          "Ramos",
          "Lahm",
        ],
      },
      active: {
        id: "active",
        label: "Jugadores actuales",
        words: [
          "Messi",
          "Cristiano Ronaldo",
          "Neymar",
          "Mbappé",
          "Haaland",
          "Benzema",
          "Lewandowski",
          "Salah",
          "De Bruyne",
          "Modrić",
          "Kroos",
          "Casemiro",
          "Kanté",
          "Pogba",
          "Bruno Fernandes",
          "Son Heung-min",
          "Kane",
          "Grealish",
          "Foden",
          "Bellingham",
          "Pedri",
          "Gavi",
          "Ansu Fati",
          "Vinícius Jr",
          "Rodrygo",
          "Tchouaméni",
          "Camavinga",
          "Osimhen",
          "Kvara",
          "Lautaro Martínez",
        ],
      },
      national: {
        id: "national",
        label: "Selecciones",
        words: [
          "Argentina",
          "Brasil",
          "Francia",
          "España",
          "Inglaterra",
          "Alemania",
          "Italia",
          "Portugal",
          "Holanda",
          "Bélgica",
          "Croacia",
          "Uruguay",
          "Colombia",
          "México",
          "Estados Unidos",
          "Marruecos",
          "Senegal",
          "Ghana",
          "Nigeria",
          "Japón",
          "Corea del Sur",
          "Australia",
          "Polonia",
          "Dinamarca",
          "Suecia",
          "Noruega",
          "Suiza",
          "Austria",
          "República Checa",
          "Ucrania",
        ],
      },
      wc: {
        id: "wc",
        label: "Mundiales",
        words: [
          "Qatar 2022",
          "Rusia 2018",
          "Brasil 2014",
          "Sudáfrica 2010",
          "Alemania 2006",
          "Corea-Japón 2002",
          "Francia 1998",
          "Estados Unidos 1994",
          "Italia 1990",
          "México 1986",
          "España 1982",
          "Argentina 1978",
          "Alemania 1974",
          "México 1970",
          "Inglaterra 1966",
          "Chile 1962",
          "Suecia 1958",
          "Suiza 1954",
          "Brasil 1950",
          "Francia 1938",
          "Italia 1934",
          "Uruguay 1930",
          "Copa del Mundo",
          "FIFA",
          "Lusail",
          "Maracaná",
          "Wembley",
          "Azteca",
          "San Siro",
          "Bernabéu",
        ],
      },
      libertadores: {
        id: "libertadores",
        label: "Copa Libertadores",
        words: [
          "Copa Libertadores",
          "CONMEBOL",
          "Boca Juniors",
          "River Plate",
          "Independiente",
          "Estudiantes",
          "Racing",
          "San Lorenzo",
          "Flamengo",
          "Palmeiras",
          "Santos",
          "São Paulo",
          "Corinthians",
          "Grêmio",
          "Internacional",
          "Atlético Mineiro",
          "Colo-Colo",
          "Universidad de Chile",
          "Peñarol",
          "Nacional",
          "Olimpia",
          "Cerro Porteño",
          "LDU Quito",
          "Barcelona SC",
          "Millonarios",
          "Atlético Nacional",
          "Once Caldas",
          "Deportivo Cali",
          "Caracas FC",
          "La Guaira",
        ],
      },
      ucl: {
        id: "ucl",
        label: "Champions League",
        words: [
          "Champions League",
          "UEFA",
          "Real Madrid",
          "Barcelona",
          "Atlético Madrid",
          "Manchester City",
          "Manchester United",
          "Liverpool",
          "Chelsea",
          "Arsenal",
          "Bayern Munich",
          "Borussia Dortmund",
          "PSG",
          "AC Milan",
          "Inter Milan",
          "Juventus",
          "Napoli",
          "Porto",
          "Benfica",
          "Ajax",
          "PSV",
          "Shakhtar",
          "Dinamo Zagreb",
          "Red Star",
          "Celtic",
          "Rangers",
          "Galatasaray",
          "Fenerbahçe",
          "Olympiacos",
          "PAOK",
        ],
      },
    },
  },
  {
    id: "movies",
    label: "Cine",
    icon: "🎬",
    description: "Películas, actores, directores famosos",
    words: [
      "Titanic",
      "Avatar",
      "Avengers",
      "Star Wars",
      "Harry Potter",
      "Batman",
      "Leonardo DiCaprio",
      "Brad Pitt",
      "Scarlett Johansson",
      "Tom Hanks",
      "Spielberg",
      "Tarantino",
      "Christopher Nolan",
      "Martin Scorsese",
      "Oscar",
      "Hollywood",
      "Netflix",
      "Disney",
      "Marvel",
      "DC Comics",
      "Thriller",
      "Comedia",
      "Drama",
      "Acción",
      "Terror",
      "Ciencia ficción",
    ],
    subThemes: {
      classics: {
        id: "classics",
        label: "Clásicos",
        words: [
          "Casablanca",
          "El Padrino",
          "Ciudadano Kane",
          "Psicosis",
          "Vértigo",
          "Cantando bajo la lluvia",
          "Lo que el viento se llevó",
          "El mago de Oz",
          "Sunset Boulevard",
          "La dolce vita",
          "8½",
          "Los siete samuráis",
          "Rashomon",
          "El acorazado Potemkin",
          "Metrópolis",
          "El gabinete del Dr. Caligari",
          "Nosferatu",
          "King Kong",
          "Ben-Hur",
          "Lawrence de Arabia",
        ],
      },
      marvel: {
        id: "marvel",
        label: "Marvel",
        words: [
          "Iron Man",
          "Capitán América",
          "Thor",
          "Hulk",
          "Viuda Negra",
          "Hawkeye",
          "Spider-Man",
          "Doctor Strange",
          "Capitana Marvel",
          "Ant-Man",
          "Guardianes de la Galaxia",
          "Pantera Negra",
          "Wanda",
          "Visión",
          "Falcon",
          "Soldado del Invierno",
          "Loki",
          "Thanos",
          "Infinity War",
          "Endgame",
          "Tony Stark",
          "Steve Rogers",
          "Natasha Romanoff",
          "Bruce Banner",
          "Peter Parker",
          "Stephen Strange",
          "Carol Danvers",
          "Scott Lang",
          "T'Challa",
          "Wakanda",
        ],
      },
      directors: {
        id: "directors",
        label: "Directores",
        words: [
          "Steven Spielberg",
          "Martin Scorsese",
          "Quentin Tarantino",
          "Christopher Nolan",
          "Stanley Kubrick",
          "Alfred Hitchcock",
          "Francis Ford Coppola",
          "Ridley Scott",
          "James Cameron",
          "George Lucas",
          "Tim Burton",
          "David Fincher",
          "Woody Allen",
          "Pedro Almodóvar",
          "Alejandro González Iñárritu",
          "Guillermo del Toro",
          "Denis Villeneuve",
          "Jordan Peele",
          "Greta Gerwig",
          "Chloé Zhao",
          "Bong Joon-ho",
          "Akira Kurosawa",
          "Federico Fellini",
          "Ingmar Bergman",
          "Andrei Tarkovsky",
          "Jean-Luc Godard",
          "François Truffaut",
          "Luis Buñuel",
          "Orson Welles",
          "Billy Wilder",
        ],
      },
    },
  },
  {
    id: "politics",
    label: "Política",
    icon: "🏛️",
    description: "Líderes mundiales, instituciones, conceptos políticos",
    words: [
      "Presidente",
      "Congreso",
      "Senado",
      "Constitución",
      "Democracia",
      "Biden",
      "Trump",
      "Putin",
      "Xi Jinping",
      "Macron",
      "Merkel",
      "ONU",
      "OTAN",
      "Unión Europea",
      "Casa Blanca",
      "Kremlin",
      "Elecciones",
      "Voto",
      "Campaña",
      "Partido político",
      "Oposición",
      "Izquierda",
      "Derecha",
      "Centro",
      "Liberal",
      "Conservador",
      "Socialista",
    ],
    subThemes: {
      argentina: {
        id: "argentina",
        label: "Política Argentina",
        words: [
          "Javier Milei",
          "Alberto Fernández",
          "Cristina Kirchner",
          "Mauricio Macri",
          "Sergio Massa",
          "Patricia Bullrich",
          "Horacio Rodríguez Larreta",
          "Axel Kicillof",
          "Casa Rosada",
          "Congreso Nacional",
          "Senado",
          "Diputados",
          "Corte Suprema",
          "Peronismo",
          "Radicalismo",
          "PRO",
          "La Libertad Avanza",
          "Frente de Todos",
          "Juntos por el Cambio",
          "CGT",
          "CTA",
          "UIA",
          "Campo",
          "Retenciones",
          "Cepo",
          "Inflación",
          "FMI",
          "PASO",
          "Ballotage",
          "Gobernador",
        ],
      },
      international: {
        id: "international",
        label: "Política Internacional",
        words: [
          "Joe Biden",
          "Donald Trump",
          "Vladimir Putin",
          "Xi Jinping",
          "Emmanuel Macron",
          "Olaf Scholz",
          "Rishi Sunak",
          "Giorgia Meloni",
          "Pedro Sánchez",
          "Justin Trudeau",
          "Volodymyr Zelensky",
          "Benjamin Netanyahu",
          "Recep Erdogan",
          "Mohammed bin Salman",
          "Narendra Modi",
          "Lula da Silva",
          "AMLO",
          "Gabriel Boric",
          "Gustavo Petro",
          "Casa Blanca",
          "Kremlin",
          "Elíseo",
          "Downing Street",
          "Bundestag",
          "Congreso",
          "Duma",
          "Knesset",
          "G7",
          "G20",
          "BRICS",
        ],
      },
    },
  },
  {
    id: "music",
    label: "Música",
    icon: "🎵",
    description: "Artistas, géneros, instrumentos musicales",
    words: [
      "Beatles",
      "Queen",
      "Michael Jackson",
      "Madonna",
      "Elvis",
      "Bob Dylan",
      "Taylor Swift",
      "Drake",
      "Beyoncé",
      "Ed Sheeran",
      "Adele",
      "Billie Eilish",
      "Rock",
      "Pop",
      "Jazz",
      "Blues",
      "Reggae",
      "Hip Hop",
      "Clásica",
      "Guitarra",
      "Piano",
      "Batería",
      "Violín",
      "Saxofón",
      "Trompeta",
      "Grammy",
      "Spotify",
      "iTunes",
      "Concierto",
      "Festival",
      "Álbum",
    ],
    subThemes: {
      rock: {
        id: "rock",
        label: "Rock",
        words: [
          "The Beatles",
          "Led Zeppelin",
          "Pink Floyd",
          "The Rolling Stones",
          "Queen",
          "AC/DC",
          "Metallica",
          "Nirvana",
          "Guns N' Roses",
          "U2",
          "Radiohead",
          "Pearl Jam",
          "Red Hot Chili Peppers",
          "Foo Fighters",
          "Green Day",
          "Linkin Park",
          "Coldplay",
          "Muse",
          "Arctic Monkeys",
          "The Strokes",
          "John Lennon",
          "Paul McCartney",
          "Freddie Mercury",
          "Robert Plant",
          "Jimmy Page",
          "David Gilmour",
          "Mick Jagger",
          "Kurt Cobain",
          "Eddie Vedder",
          "Bono",
        ],
      },
      latin: {
        id: "latin",
        label: "Música Latina",
        words: [
          "Shakira",
          "Bad Bunny",
          "J Balvin",
          "Maluma",
          "Karol G",
          "Rosalía",
          "Daddy Yankee",
          "Luis Fonsi",
          "Ozuna",
          "Anuel AA",
          "Soda Stereo",
          "Gustavo Cerati",
          "Charly García",
          "Fito Páez",
          "Los Fabulosos Cadillacs",
          "Manu Chao",
          "Jesse & Joy",
          "Maná",
          "Julieta Venegas",
          "Natalia Lafourcade",
          "Mon Laferte",
          "Álvaro Soler",
          "Mau y Ricky",
          "Camila Cabello",
          "Becky G",
          "Natti Natasha",
          "Thalía",
          "Luis Miguel",
          "Marc Anthony",
          "Ricky Martin",
        ],
      },
    },
  },
  {
    id: "random",
    label: "Random",
    icon: "🎲",
    description: "Palabras variadas de diferentes categorías",
    words: [
      "Pizza",
      "Café",
      "Playa",
      "Montaña",
      "Libro",
      "Teléfono",
      "Coche",
      "Perro",
      "Gato",
      "Árbol",
      "Flor",
      "Sol",
      "Luna",
      "Estrella",
      "Casa",
      "Escuela",
      "Hospital",
      "Parque",
      "Museo",
      "Teatro",
      "Agua",
      "Fuego",
      "Tierra",
      "Aire",
      "Tiempo",
      "Espacio",
      "Amor",
      "Amistad",
      "Familia",
      "Trabajo",
      "Dinero",
      "Salud",
    ],
  },
]

export function getRandomWords(words: string[], count: number): string[] {
  const shuffled = [...words].sort(() => 0.5 - Math.random())
  const selectedWord = shuffled[0]
  return Array(count).fill(selectedWord)
}

export function getThemeById(id: string): Theme | undefined {
  return themes.find((theme) => theme.id === id)
}

export function getSubThemeWords(themeId: string, subThemeId: string): string[] {
  const theme = getThemeById(themeId)
  if (!theme) return []

  if (subThemeId === "general") {
    return theme.words
  }

  return theme.subThemes?.[subThemeId]?.words ?? theme.words
}
